
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Fan Yang
tagline: Full Stack Developer
pic: minion.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: shevapato2008@gmail.com
phone: XXX XXX XXXX
website: blog.yangfrank.com #do not add http://
linkedin: shevapato2008
github: shevapato2008
twitter: '@shevapato2008'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
